version: '3.4'
services:
  restVerticle:
    image: restdocker
    restart: always
    build: /restApp/src/main/docker/Rest
    expose:
      - "8888"
    ports:
      - "5101:8888"
  orderVerticle:
    image: orderdocker
    restart: always
    build: /orderApp/src/main/docker/Order
    expose:
      - "8888"
    ports:
      - "5102:8888"

